/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GetQuoteRouteImport } from './routes/get-quote'
import { Route as GraphicDesigningRouteImport } from './routes/graphic-designing'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as PrintingProductsRouteImport } from './routes/printing-products'
import { Route as ProcessRouteImport } from './routes/process'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GetQuoteRoute = GetQuoteRouteImport.update({
  id: '/get-quote',
  path: '/get-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicDesigningRoute = GraphicDesigningRouteImport.update({
  id: '/graphic-designing',
  path: '/graphic-designing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintingProductsRoute = PrintingProductsRouteImport.update({
  id: '/printing-products',
  path: '/printing-products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/get-quote': typeof GetQuoteRoute
  '/graphic-designing': typeof GraphicDesigningRoute
  '/industries': typeof IndustriesRoute
  '/printing-products': typeof PrintingProductsRoute
  '/process': typeof ProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/get-quote': typeof GetQuoteRoute
  '/graphic-designing': typeof GraphicDesigningRoute
  '/industries': typeof IndustriesRoute
  '/printing-products': typeof PrintingProductsRoute
  '/process': typeof ProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/get-quote': typeof GetQuoteRoute
  '/graphic-designing': typeof GraphicDesigningRoute
  '/industries': typeof IndustriesRoute
  '/printing-products': typeof PrintingProductsRoute
  '/process': typeof ProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/get-quote'
    | '/graphic-designing'
    | '/industries'
    | '/printing-products'
    | '/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/get-quote'
    | '/graphic-designing'
    | '/industries'
    | '/printing-products'
    | '/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/get-quote'
    | '/graphic-designing'
    | '/industries'
    | '/printing-products'
    | '/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GetQuoteRoute: typeof GetQuoteRoute
  GraphicDesigningRoute: typeof GraphicDesigningRoute
  IndustriesRoute: typeof IndustriesRoute
  PrintingProductsRoute: typeof PrintingProductsRoute
  ProcessRoute: typeof ProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-quote': {
      id: '/get-quote'
      path: '/get-quote'
      fullPath: '/get-quote'
      preLoaderRoute: typeof GetQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphic-designing': {
      id: '/graphic-designing'
      path: '/graphic-designing'
      fullPath: '/graphic-designing'
      preLoaderRoute: typeof GraphicDesigningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printing-products': {
      id: '/printing-products'
      path: '/printing-products'
      fullPath: '/printing-products'
      preLoaderRoute: typeof PrintingProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GetQuoteRoute: GetQuoteRoute,
  GraphicDesigningRoute: GraphicDesigningRoute,
  IndustriesRoute: IndustriesRoute,
  PrintingProductsRoute: PrintingProductsRoute,
  ProcessRoute: ProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
